import type { Metadata } from "next";
import ThemeProvider from "./theme-provider";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Wrapper from "@/components/Wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={poppins.className}>
      <body className="bg-background dark:bg-dark-background text-smooth-black dark:text-white">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Wrapper>
            <Navbar />
            {children}
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
